# fly.toml app configuration file generated for signature-aggregator-fuji on 2025-01-29T05:27:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'signature-aggregator-fuji'
primary_region = 'ewr'

[build]
  dockerfile = "signature-aggregator/Dockerfile"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
